### ISSUE TITLE
Crash during intro videos

### ISSUE THREAD

**Issue by buvk** [PARTYMANX/partymod-thps2#10] opened 2024-06-26 04:26 UTC
If you have windowed unchecked, and have borderless checked/unchecked, the game crashes if you alt tab to a different window during the intro videos.

**Comment by PARTYMANX** [comment] 2024-06-26 05:11
looks like the issue is that i forgot to disable rendering on the video player when the window is minimized.  Good catch

**Comment by PARTYMANX** [comment] 2024-08-16 23:02
fixed in latest release

**Closed by PARTYMANX** 2024-08-16 23:02 UTC
